import Head from "next/head";
import { useState } from "react";
import Header from "../comps/Header";
import Main from "../comps/Main";
import Rules from "../comps/Rules";
import Game from "../comps/Game";

const Home = () => {
  const [showRules, setShowRules] = useState(false);
  const [showGame, setShowGame] = useState(false);
  const [showMain, setShowMain] = useState(true);
  const [pick, setPick] = useState("");
  const [score, setScore] = useState(0);

  const showGameScreen = (e) => {
    setPick(e);
    setShowGame(!showGame);
    setShowMain(!showMain);
  };

  const showHome = () => {
    setShowMain(!showMain);
    setShowGame(!showGame);
  };

  return (
    <>
      <Head>
        <title>Frontend Mentor | Rock Paper Scissors Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header score={score} />
      {showMain ? <Main showGame={(e) => showGameScreen(e)} /> : ""}
      {showGame ? (
        <Game
          increment={() => setScore(score + 1)}
          decrement={() => (score == 0 ? null : setScore(score - 1))}
          goHome={showHome}
          pick={pick}
        />
      ) : (
        ""
      )}
      {showRules ? <Rules hide={(e) => setShowRules(e)} /> : ""}
      <div onClick={() => setShowRules(!showRules)} className="rules">
        RULES
      </div>
    </>
  );
};

export default Home;
